FRAMEWORK_VERSION = "1.4.0-alpha.1"
PROTOCOL_VERSION = "2.3.0-alpha.1"
SCHEMA_PREFIX = "org-agent-mesh"
AUTHORITY_TIERS = ("ORCHESTRATOR", "REVIEWER", "SPECIALIST")
DEPLOYMENT_ROLES = ("PRIMARY", "MANAGER", "RESEARCH")
MESSAGE_KINDS = (
    "CLAIM", "FINDING", "BLOCKER", "REQUEST", "REVIEW_REQUEST", "REVIEW_DISPOSITION",
    "CONTRADICTION", "HANDOFF", "DECISION", "SUPERSESSION", "SERVICE_CHECKPOINT", "RELEASE_CLOSE"
)
CAPABILITIES = (
    "READ_SOURCE", "WRITE_WORKING_ARTIFACTS", "WRITE_ACCEPTED_STATE", "SEND_EXTERNAL_COMMUNICATION",
    "MODIFY_EXTERNAL_SYSTEM", "DELETE_DATA", "ACCESS_SENSITIVE_DATA", "APPROVE_RELEASE",
    "AUTHORIZE_FINANCIAL_ACTION", "AUTHORIZE_POLICY_CHANGE", "CROSS_PROJECT_EXCHANGE",
    "BUILD_DEPLOYMENT_PACKAGE", "PUBLISH_DEPLOYMENT_PACKAGE"
)
